import { EntityConfig } from "./types";

const dateFilters = (field: string, label: string) => ({ key: field, label, type: "dateRange" as const });
const dateTimeFilters = (field: string, label: string) => ({ key: field, label, type: "dateTime" as const });
const numberFilters = (field: string, label: string) => ({ key: field, label, type: "numberRange" as const });
const textFilter = (field: string, label: string) => ({ key: field, label, type: "text" as const });



export const entityConfigs: Record<string, EntityConfig> = {
  users: {
    title: "Пользователи",
    endpoint: "/users",
    columns: [
      { key: "fullName", label: "ФИО" },
      { key: "email", label: "Email" },
      { key: "role", label: "Роль" },
      { key: "createdAt", label: "Создан" },
    ],
    filters: [
      textFilter("fullName", "ФИО"),
      textFilter("email", "Email"),
      { key: "role", label: "Роль", type: "select", options: ["admin", "teacher"] },
      dateFilters("createdAt", "Дата создания"),
    ],
    createTemplate: { email: "", passwordHash: "", fullName: "", role: "teacher" },
  },
  universities: {
    title: "Вузы",
    endpoint: "/universities",
    columns: [
      { key: "name", label: "Название" },
      { key: "shortName", label: "Кратко" },
      { key: "externalCode", label: "Код" },
    ],
    filters: [textFilter("name", "Название"), textFilter("shortName", "Кратко"), textFilter("externalCode", "Код")],
    createTemplate: { name: "", shortName: "", externalCode: "" },
  },
  uploads: {
    title: "История загрузок",
    endpoint: "/uploads",
    columns: [
      { key: "_id", label: "ID" },
      { key: "importBatchId", label: "Пачка" },
      { key: "status", label: "Статус" },
      { key: "filesCount", label: "Файлов" },
      { key: "totalRows", label: "Строк" },
      { key: "matchedStudents", label: "Студентов" },
      { key: "createdAt", label: "Создана" },
    ],
    filters: [
      { key: "status", label: "Статус", type: "select", options: ["pending", "processing", "done", "done_with_warnings", "error"] },
      textFilter("importBatchId", "ID пачки"),
      dateFilters("createdAt", "Дата создания"),
      numberFilters("filesCount", "Количество файлов"),
      numberFilters("totalRows", "Количество строк"),
      numberFilters("matchedStudents", "Сопоставлено студентов"),
    ],
    createTemplate: {},
  },
  students: {
    title: "Студенты",
    endpoint: "/students",
    columns: [
      { key: "fullName", label: "ФИО" },
      { key: "externalId", label: "Внешний ID" },
      { key: "recordBookNumber", label: "Зачётка" },
      { key: "email", label: "Email" },
      { key: "program", label: "Программа" },
      { key: "educationLevel", label: "Уровень" },
      { key: "group", label: "Группа" },
    ],
    filters: [
      textFilter("fullName", "ФИО"),
      textFilter("externalId", "Внешний ID"),
      textFilter("recordBookNumber", "Зачётка"),
      textFilter("email", "Email"),
      textFilter("faculty", "Факультет"),
      textFilter("program", "Программа"),
      { key: "educationLevel", label: "Уровень обучения", type: "select", options: ["bachelor", "master", "specialist"] },
      textFilter("group", "Группа"),
    ],
    createTemplate: {
      externalId: "",
      recordBookNumber: "",
      fullName: "",
      email: "",
      faculty: "",
      program: "",
      educationLevel: "bachelor",
      group: "",
      faceEmbedding: [],
    },
  },
  events: {
    title: "Таймлайн событий",
    endpoint: "/timeline-events",
    columns: [
      { key: "eventType", label: "Тип" },
      { key: "eventTime", label: "Время" },
      { key: "sourceFileKey", label: "Файл" },
      { key: "moodle.action", label: "Moodle action" },
      { key: "moodle.target", label: "Цель" },
    ],
    filters: [
      { key: "eventType", label: "Тип события", type: "select", options: ["moodle", "ocr_frame", "system"] },
      dateFilters("eventTime", "Время события"),
      textFilter("sourceFileKey", "Файл"),
      textFilter("moodle.action", "Действие Moodle"),
      textFilter("moodle.courseName", "Имя курса"),
      textFilter("moodle.target", "Цель Moodle"),
      textFilter("student.group", "Группа студента"),
      textFilter("student.program", "Программа студента"),
      { key: "student.educationLevel", label: "Уровень обучения", type: "select", options: ["bachelor", "master", "specialist"] },
      numberFilters("moodle.timeSpent", "Время на вопрос"),
    ],
    createTemplate: { eventType: "system", eventTime: "", system: { code: "", message: "" } },
  },
  sessions: {
    title: "Сессии",
    endpoint: "/sessions",
    detailTitleKey: "examName",
    detailBackPath: "/sessions",
    columns: [
      { key: "examName", label: "Экзамен" },
      { key: "courseName", label: "Имя курса" },
      { key: "student.group", label: "Группа студента" },
      { key: "student.program", label: "Программа студента" },
      { key: "student.educationLevel", label: "Уровень обучения" },
      { key: "startTime", label: "Начало" },
      { key: "durationMinutes", label: "Длительность" },
      { key: "metrics.combined.riskLevel", label: "Риск" },
      { key: "metrics.combined.anomalyScore", label: "Аномальность" },
    ],
    filters: [
      textFilter("examName", "Экзамен"),
      textFilter("courseName", "Имя курса"),
      textFilter("student.group", "Группа студента"),
      textFilter("student.program", "Программа студента"),
      { key: "student.educationLevel", label: "Уровень обучения", type: "select", options: ["bachelor", "master", "specialist"] },
      { key: "metrics.combined.riskLevel", label: "Риск", type: "select", options: ["low", "medium", "high"] },
      dateTimeFilters("startTime", "Начало"),
      numberFilters("durationMinutes", "Длительность"),
      numberFilters("metrics.combined.anomalyScore", "Балл аномальности"),
    ],
    createTemplate: {
      examName: "",
      startTime: "",
      endTime: "",
      durationMinutes: 0,
      metrics: {},
      featureVector: [],
    },
  },
  runs: {
    title: "История запусков кластеризации",
    endpoint: "/clustering-runs",
    columns: [
      { key: "_id", label: "ID" },
      { key: "algorithm", label: "Алгоритм" },
      { key: "status", label: "Статус" },
      { key: "results.totalSessions", label: "Сессий" },
      { key: "results.clusterCount", label: "Кластеров" },
      { key: "results.anomalyCount", label: "Аномалий" },
    ],
    filters: [
      { key: "algorithm", label: "Алгоритм", type: "select", options: ["kmeans", "dbscan"] },
      { key: "status", label: "Статус", type: "select", options: ["running", "done", "error"] },
      dateFilters("startedAt", "Начало"),
      numberFilters("results.totalSessions", "Количество сессий"),
      numberFilters("results.anomalyCount", "Количество аномалий"),
    ],
    createTemplate: { algorithm: "kmeans", status: "done", parameters: {}, results: {} },
  },
  audit: {
    title: "Аудит действий",
    endpoint: "/audit-logs",
    columns: [
      { key: "actorType", label: "Субъект" },
      { key: "action", label: "Действие" },
      { key: "entityType", label: "Сущность" },
      { key: "occurredAt", label: "Время" },
    ],
    filters: [
      { key: "actorType", label: "Тип субъекта", type: "select", options: ["user", "system"] },
      textFilter("action", "Действие"),
      textFilter("entityType", "Сущность"),
      dateFilters("occurredAt", "Время"),
    ],
    createTemplate: {},
  },
};
